/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/8.0.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("org.teavm") version "0.12.3"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.1")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:31.1-jre")

    // This dependency is used by TeaVM
    // implementation("teavm.libs.jsoApis")
}

teavm {
    all {
	mainClass.set("craftinginterpreters.trick.Trick")
    }
    js {
	addedToWebApp.set(true)

        // this is also optional, default value is <project name>.js
        targetFileName.set("example.js")
    }
}

// application {
//     // Define the main class for the application.
//     mainClass.set("craftinginterpreters.trick.Trick")
// }

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
